/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package pratikum15062026;

import javax.swing.JOptionPane;

/**
 *
 * @author Muhammad Zikri
 */
public class Penilaian extends javax.swing.JFrame {

    /**
     * Creates new form Penilaian
     */
    public Penilaian() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbljudul = new javax.swing.JLabel();
        lblnama = new javax.swing.JLabel();
        lblkelas = new javax.swing.JLabel();
        lblmatkul = new javax.swing.JLabel();
        lbltugas = new javax.swing.JLabel();
        lblquiz = new javax.swing.JLabel();
        lbluts = new javax.swing.JLabel();
        lbluas = new javax.swing.JLabel();
        txtnama = new javax.swing.JTextField();
        txtkelas = new javax.swing.JTextField();
        txtmatkul = new javax.swing.JTextField();
        txttugas = new javax.swing.JTextField();
        txtquiz = new javax.swing.JTextField();
        txtuts = new javax.swing.JTextField();
        txtuas = new javax.swing.JTextField();
        proses = new javax.swing.JButton();
        lblakhir = new javax.swing.JLabel();
        txtakhir = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        txtkonfeksi = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lbljudul.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lbljudul.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbljudul.setText("Form Penilaian Mahasiswa");

        lblnama.setText("Nama Mahasiswa :");

        lblkelas.setText("Kelas                     :");

        lblmatkul.setText("Mata Kuliah          :");

        lbltugas.setText("Nilai Tugas           :");

        lblquiz.setText("Nilai  Quiz            :");

        lbluts.setText("Nilai UTS             :");

        lbluas.setText("Nilai UAS             :");

        txtnama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnamaActionPerformed(evt);
            }
        });

        txtmatkul.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtmatkulActionPerformed(evt);
            }
        });

        txttugas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txttugasActionPerformed(evt);
            }
        });

        txtquiz.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtquizActionPerformed(evt);
            }
        });

        proses.setText("Proses");
        proses.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                prosesActionPerformed(evt);
            }
        });

        lblakhir.setText("NIlai Akhir :");

        txtakhir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtakhirActionPerformed(evt);
            }
        });

        jLabel1.setText("Konversi Nilai :");

        txtkonfeksi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtkonfeksiActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(182, 182, 182)
                        .addComponent(lbljudul))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(lblnama, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                            .addComponent(lbluas, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lbluts, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblquiz, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lbltugas, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblmatkul, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblkelas, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(15, 15, 15)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtnama, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txtmatkul)
                                .addComponent(txttugas)
                                .addComponent(txtquiz)
                                .addComponent(txtuts)
                                .addComponent(txtuas, javax.swing.GroupLayout.DEFAULT_SIZE, 182, Short.MAX_VALUE)
                                .addComponent(txtkelas)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(41, 41, 41)
                                .addComponent(proses, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblakhir, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(24, 24, 24)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtkonfeksi, javax.swing.GroupLayout.DEFAULT_SIZE, 76, Short.MAX_VALUE)
                                    .addComponent(txtakhir))
                                .addGap(3, 3, 3)))))
                .addGap(16, 16, 16))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(lbljudul)
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblnama)
                    .addComponent(txtnama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblkelas)
                    .addComponent(txtkelas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblmatkul)
                            .addComponent(txtmatkul, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbltugas)
                            .addComponent(txttugas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(proses)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblquiz)
                    .addComponent(txtquiz, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblakhir)
                    .addComponent(txtakhir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbluts)
                    .addComponent(txtuts, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(txtkonfeksi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbluas)
                    .addComponent(txtuas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(54, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtnamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnamaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnamaActionPerformed

    private void txtmatkulActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtmatkulActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtmatkulActionPerformed

    private void txttugasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txttugasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txttugasActionPerformed

    private void txtquizActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtquizActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtquizActionPerformed

    private void txtakhirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtakhirActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtakhirActionPerformed

    private void prosesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_prosesActionPerformed
        String nama = txtnama.getText();
        String kelas = txtkelas.getText();
        String matkul = txtmatkul.getText();
        
        if (nama.isEmpty() || kelas.isEmpty() || matkul.isEmpty()){
            JOptionPane.showMessageDialog(this,"Nama harus diisi","Peringatan",JOptionPane.WARNING_MESSAGE);
            txtnama.setText(" ");
            txtnama.requestFocus();
            
        }
        
        if (txttugas.getText().isEmpty()|| txtquiz.getText().isEmpty() || txtuts.getText().isEmpty() || txtuas.getText().isEmpty()){
            JOptionPane.showMessageDialog(this, "Semua nilai harus diisi");
             
        }
        
        try{
        double tugas = validasiNilai (txttugas.getText(),"Tugas");
        double quiz = validasiNilai (txtquiz.getText(),"QUiz");
        double uts = validasiNilai (txtuts.getText(),"UTS");
        double uas = validasiNilai (txtuas.getText(),"UAS");
        
        double na = 0.15*tugas+0.20*quiz+0.30*uts+0.30*uas;
        txtakhir.setText(Double.toString(na));
        
        String nh= "";
        if (na >= 80 && na <= 100) {
            nh = "A";
        } else if (na >= 65 && na <80){
            nh ="B";
        } else if (na >=55 && na <65){
            nh = "C";
        } else {
            nh ="D";
        }
        
        txtkonfeksi.setText(nh);
        
        
        JOptionPane.showMessageDialog(this,"Nama :"+nama+ "\nKelas :"+kelas+ "\nMata Kuliah :"+matkul+ "\nNilai Akhir :"+na+ "\nGrade :"+nh, "Hasil Penilaian", JOptionPane.INFORMATION_MESSAGE);
        
        }catch(Exception e){
            JOptionPane.showMessageDialog(this,e.getMessage(),"Validasi Nilai",JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_prosesActionPerformed

    private void txtkonfeksiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtkonfeksiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtkonfeksiActionPerformed

    private double validasiNilai(String input, String jenisNilai) throws Exception {
        double nilai = Double.parseDouble(input);
        if (nilai <0 || nilai >100)
            throw new Exception (jenisNilai+ " harus antara 0 - 100");
        return nilai;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Penilaian.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Penilaian.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Penilaian.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Penilaian.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Penilaian().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblakhir;
    private javax.swing.JLabel lbljudul;
    private javax.swing.JLabel lblkelas;
    private javax.swing.JLabel lblmatkul;
    private javax.swing.JLabel lblnama;
    private javax.swing.JLabel lblquiz;
    private javax.swing.JLabel lbltugas;
    private javax.swing.JLabel lbluas;
    private javax.swing.JLabel lbluts;
    private javax.swing.JButton proses;
    private javax.swing.JTextField txtakhir;
    private javax.swing.JTextField txtkelas;
    private javax.swing.JTextField txtkonfeksi;
    private javax.swing.JTextField txtmatkul;
    private javax.swing.JTextField txtnama;
    private javax.swing.JTextField txtquiz;
    private javax.swing.JTextField txttugas;
    private javax.swing.JTextField txtuas;
    private javax.swing.JTextField txtuts;
    // End of variables declaration//GEN-END:variables
}
