/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package pratikum22062026;

import javax.swing.JOptionPane;

/**
 *
 * @author Muhammad Zikri
 */
public class formGaji extends javax.swing.JFrame {

    /**
     * Creates new form formGaji
     */
    public formGaji() {
        initComponents();
        txtgapok.setEditable(false);
        txtlembur.setEditable(false);
        txttotal.setEditable(false);
        txtpajak.setEditable(false);
        txtgajibersih.setEditable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        golongan = new javax.swing.ButtonGroup();
        lembur = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtnama = new javax.swing.JTextField();
        rbtidaknikah = new javax.swing.JRadioButton();
        rbnikah = new javax.swing.JRadioButton();
        cbgolongan = new javax.swing.JComboBox<>();
        btgapok = new javax.swing.JButton();
        txtgapok = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        rbya = new javax.swing.JRadioButton();
        rbtidaklembur = new javax.swing.JRadioButton();
        jLabel6 = new javax.swing.JLabel();
        cblembur = new javax.swing.JComboBox<>();
        txtlembur = new javax.swing.JTextField();
        btlembur = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        txttotal = new javax.swing.JTextField();
        txtgajibersih = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        txtpajak = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setText("  Form Gaji Karyawan");

        jLabel2.setText("Nama");

        jLabel3.setText("Golongan");

        jLabel4.setText("Status");

        golongan.add(rbtidaknikah);
        rbtidaknikah.setText("Tidak Menikah");
        rbtidaknikah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtidaknikahActionPerformed(evt);
            }
        });

        golongan.add(rbnikah);
        rbnikah.setText("Menikah");
        rbnikah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbnikahActionPerformed(evt);
            }
        });

        cbgolongan.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Golongan", "1", "2", "3", "4" }));
        cbgolongan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbgolonganActionPerformed(evt);
            }
        });

        btgapok.setText("Gaji Pokok");
        btgapok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btgapokActionPerformed(evt);
            }
        });

        txtgapok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtgapokActionPerformed(evt);
            }
        });

        jLabel5.setText("Lembur");

        lembur.add(rbya);
        rbya.setText("Ya");
        rbya.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbyaActionPerformed(evt);
            }
        });

        lembur.add(rbtidaklembur);
        rbtidaklembur.setText("Tidak");

        jLabel6.setText("Jam Lembur");

        cblembur.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Total Jam", "1 Jam", "2 Jam", "3 Jam" }));
        cblembur.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cblemburActionPerformed(evt);
            }
        });

        txtlembur.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtlemburActionPerformed(evt);
            }
        });

        btlembur.setText("Gaji Lembur");
        btlembur.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btlemburActionPerformed(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jButton1.setText("Hitung Total");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel8.setText("Total Gaji");

        txttotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txttotalActionPerformed(evt);
            }
        });

        txtgajibersih.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtgajibersihActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel9.setText("Gaji Bersih");

        jButton2.setText("Reset");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Keluar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jLabel7.setText("Pajak");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 64, Short.MAX_VALUE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(cbgolongan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(rbtidaknikah)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(rbnikah))
                                .addComponent(txtnama))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(rbya)
                                .addGap(18, 18, 18)
                                .addComponent(rbtidaklembur))))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel6)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(cblembur, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(btlembur, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btgapok, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtlembur)
                            .addComponent(txttotal)
                            .addComponent(txtgajibersih, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtgapok, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtpajak))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 136, Short.MAX_VALUE)
                        .addComponent(jButton2)
                        .addGap(18, 18, 18)
                        .addComponent(jButton3)
                        .addGap(63, 63, 63))))
            .addGroup(layout.createSequentialGroup()
                .addGap(208, 208, 208)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtnama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(rbtidaknikah)
                            .addComponent(rbnikah)
                            .addComponent(jLabel4)
                            .addComponent(btgapok)
                            .addComponent(txtgapok, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cbgolongan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(rbya)
                            .addComponent(rbtidaklembur)
                            .addComponent(txtlembur, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btlembur))
                        .addGap(12, 12, 12)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(cblembur, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txttotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(11, 11, 11)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(txtpajak, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(txtgajibersih, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(37, 37, 37)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, 39, Short.MAX_VALUE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rbnikahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbnikahActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbnikahActionPerformed

    private void cbgolonganActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbgolonganActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbgolonganActionPerformed

    private void rbtidaknikahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtidaknikahActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbtidaknikahActionPerformed

    private void btgapokActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btgapokActionPerformed
       String nama = txtnama.getText();
       if (nama.isEmpty()){
           JOptionPane.showMessageDialog(this,"Nama Harus diisi","Peringatan",JOptionPane.WARNING_MESSAGE);
       }
       
       if(!rbnikah.isSelected()&!rbtidaknikah.isSelected()){
           JOptionPane.showMessageDialog(this, "Status anda belum dipilih", "Pesan Kesalahan",JOptionPane.ERROR_MESSAGE);
       }
       else if (cbgolongan.getSelectedIndex()==0){
           JOptionPane.showMessageDialog(this,"Golongan belum dipilih", "Pesan Kesalahan", JOptionPane.ERROR_MESSAGE);
       }
        int gaji = (int)cbgolongan.getSelectedIndex();
        
        switch (gaji) {
            case 1 : if (rbnikah.isSelected())
                        txtgapok.setText("2600000");
                     else
                        txtgapok.setText("2500000");
            break;
            case 2 : if (rbnikah.isSelected())
                        txtgapok.setText("4150000");
                     else
                        txtgapok.setText("4000000");
            break;
            case 3 : if (rbnikah.isSelected())
                        txtgapok.setText("7200000");
                     else
                        txtgapok.setText("7000000");
            break;
            case 4 : if (rbnikah.isSelected())
                        txtgapok.setText("10000000");
                     else
                        txtgapok.setText("9750000");
            break;
            
        }
        
        
    }//GEN-LAST:event_btgapokActionPerformed

    private void txtgapokActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtgapokActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtgapokActionPerformed

    private void rbyaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbyaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbyaActionPerformed

    private void cblemburActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cblemburActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cblemburActionPerformed

    private void btlemburActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btlemburActionPerformed
       
        if(!rbya.isSelected()&!rbtidaklembur.isSelected()){
           JOptionPane.showMessageDialog(this, "Status lembur anda belum dipilih", "Pesan Kesalahan",JOptionPane.ERROR_MESSAGE);
           return;
        }
        
        if (rbya.isSelected()){
           if (cblembur.getSelectedIndex()==0){
           JOptionPane.showMessageDialog(this,"Jam lembur belum dipilih", "Pesan Kesalahan", JOptionPane.ERROR_MESSAGE);  
           return;
           }
            
        }
        
        try{
        double gaji = Double.parseDouble(txtgapok.getText());
        if (gaji <=0){
            JOptionPane.showConfirmDialog(this, "Jumlah Gaji Pokok Harus Besar Dari Nol","Pesan error",JOptionPane.ERROR_MESSAGE);
            return;
        }
        if (rbya.isSelected()){
        int lembur = (int) cblembur.getSelectedIndex();
        switch (lembur){
            case 1 : if (rbya.isSelected())
                     txtlembur.setText("25000");
                     else
                     txtlembur.setText("0");
            break;
            case 2 : if (rbya.isSelected())
                     txtlembur.setText("50000");
                     else
                     txtlembur.setText("0");
            break;
            case 3 : if (rbya.isSelected())
                     txtlembur.setText("75000");
                     else
                     txtlembur.setText("0");
            break;
        }
        } else if (rbtidaklembur.isSelected()){
            txtlembur.setText("0");
        }
        
        }catch(NumberFormatException e){
            JOptionPane.showMessageDialog(this, "Gaji pokok Harus Angka Bulat", "Pesan Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btlemburActionPerformed

    private void txttotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txttotalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txttotalActionPerformed

    private void txtgajibersihActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtgajibersihActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtgajibersihActionPerformed

    private void txtlemburActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtlemburActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtlemburActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {
            if (txtlembur.getText().isEmpty()){
                JOptionPane.showMessageDialog(this, "Hitung gapok dan lembur terlebih dahulu!","Peringatan",JOptionPane.ERROR_MESSAGE);
                
        }
                 
      double gaji = Double.parseDouble(txtgapok.getText());
      double lembur = Double.parseDouble(txtlembur.getText());
      double total = gaji + lembur ;
      double pajak = total * 0.02;
      double bersih = total - pajak;
      
      txttotal.setText(String.valueOf((long) total));
      txtpajak.setText(String.valueOf((long) pajak));
      txtgajibersih.setText(String.valueOf((long) bersih));
        }catch (NumberFormatException e) {
            
        }
      
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        txtnama.setText("");
        txtgapok.setText("");
        txtlembur.setText("");
        txtpajak.setText("");
        txttotal.setText("");
        txtgajibersih.setText("");
        cbgolongan.setSelectedIndex(0);
        cblembur.setSelectedIndex(0);
        golongan.clearSelection();
        lembur.clearSelection();
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        int pil = JOptionPane.showConfirmDialog(this, "Apakah ingin keluar ?", "Konfirmasi",JOptionPane.YES_NO_CANCEL_OPTION);
        if(pil == JOptionPane.YES_OPTION)
            System.exit(0);
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(formGaji.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(formGaji.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(formGaji.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(formGaji.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new formGaji().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btgapok;
    private javax.swing.JButton btlembur;
    private javax.swing.JComboBox<String> cbgolongan;
    private javax.swing.JComboBox<String> cblembur;
    private javax.swing.ButtonGroup golongan;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.ButtonGroup lembur;
    private javax.swing.JRadioButton rbnikah;
    private javax.swing.JRadioButton rbtidaklembur;
    private javax.swing.JRadioButton rbtidaknikah;
    private javax.swing.JRadioButton rbya;
    private javax.swing.JTextField txtgajibersih;
    private javax.swing.JTextField txtgapok;
    private javax.swing.JTextField txtlembur;
    private javax.swing.JTextField txtnama;
    private javax.swing.JTextField txtpajak;
    private javax.swing.JTextField txttotal;
    // End of variables declaration//GEN-END:variables
}
