/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package pratikum29062026;

import javax.swing.JOptionPane;

/**
 *
 * @author Muhammad Zikri
 */
public class formmakanan extends javax.swing.JFrame {

    /**
     * Creates new form formmakanan
     */
    private formutama utama;
    public formmakanan() {
        initComponents();
        txtnasgor.setEditable(false);
        txtmigor.setEditable(false);
        txtmire.setEditable(false);
        txttotalnasgor.setEditable(false);
        txttotalmigor.setEditable(false);
        txttotalmire.setEditable(false);
        txttotal.setEditable(false);
    }

    public formmakanan(formutama utama) {
        this.utama = utama;
        initComponents();
        txtnasgor.setEditable(false);
        txtmigor.setEditable(false);
        txtmire.setEditable(false);
        txttotalnasgor.setEditable(false);
        txttotalmigor.setEditable(false);
        txttotalmire.setEditable(false);
        txttotal.setEditable(false);
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        ckbnasgor = new javax.swing.JCheckBox();
        ckbmigor = new javax.swing.JCheckBox();
        ckbmire = new javax.swing.JCheckBox();
        txtnasgor = new javax.swing.JTextField();
        txtmigor = new javax.swing.JTextField();
        txtmire = new javax.swing.JTextField();
        cbnasgor = new javax.swing.JComboBox<>();
        cbmigor = new javax.swing.JComboBox<>();
        cbmire = new javax.swing.JComboBox<>();
        txttotalnasgor = new javax.swing.JTextField();
        txttotalmigor = new javax.swing.JTextField();
        txttotalmire = new javax.swing.JTextField();
        txttotal = new javax.swing.JTextField();
        btnkeluar = new javax.swing.JButton();
        btnreset = new javax.swing.JButton();
        btntotal = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel1.setText("Menu Makanan");

        ckbnasgor.setText("Nasi Goreng");
        ckbnasgor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ckbnasgorActionPerformed(evt);
            }
        });

        ckbmigor.setText("Mie Goreng");
        ckbmigor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ckbmigorActionPerformed(evt);
            }
        });

        ckbmire.setText("MIe Rebus");
        ckbmire.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ckbmireActionPerformed(evt);
            }
        });

        txtnasgor.setText("0");

        txtmigor.setText("0");

        txtmire.setText("0");

        cbnasgor.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Jumlah", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", " " }));
        cbnasgor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbnasgorActionPerformed(evt);
            }
        });

        cbmigor.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Jumlah", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", " " }));
        cbmigor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbmigorActionPerformed(evt);
            }
        });

        cbmire.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Jumlah", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", " " }));
        cbmire.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbmireActionPerformed(evt);
            }
        });

        txttotalnasgor.setText("0");
        txttotalnasgor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txttotalnasgorActionPerformed(evt);
            }
        });

        txttotalmigor.setText("0");

        txttotalmire.setText("0");

        txttotal.setText("0");

        btnkeluar.setText("Kembali");
        btnkeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnkeluarActionPerformed(evt);
            }
        });

        btnreset.setText("Reset");
        btnreset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnresetActionPerformed(evt);
            }
        });

        btntotal.setText("Total");
        btntotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btntotalActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(221, 221, 221))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(ckbnasgor, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(ckbmigor, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(ckbmire, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtnasgor, javax.swing.GroupLayout.DEFAULT_SIZE, 71, Short.MAX_VALUE)
                            .addComponent(txtmigor)
                            .addComponent(txtmire)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(113, 113, 113)
                        .addComponent(btnreset, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(43, 68, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(cbnasgor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbmigor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbmire, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(59, 59, 59)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txttotalmire, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txttotalnasgor, javax.swing.GroupLayout.DEFAULT_SIZE, 71, Short.MAX_VALUE)
                                .addComponent(txttotalmigor))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnkeluar, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(77, 77, 77))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btntotal)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txttotal, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(69, 69, 69))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ckbnasgor)
                            .addComponent(txtnasgor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbnasgor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txttotalnasgor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtmigor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ckbmigor)
                            .addComponent(cbmigor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txttotalmigor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ckbmire)
                            .addComponent(txtmire, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbmire, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txttotalmire, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 49, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txttotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btntotal))
                .addGap(53, 53, 53)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnkeluar, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnreset, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ckbnasgorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ckbnasgorActionPerformed
        txtnasgor.setText("15000");// TODO add your handling code here:
    }//GEN-LAST:event_ckbnasgorActionPerformed

    private void ckbmigorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ckbmigorActionPerformed
        txtmigor.setText("10000");// TODO add your handling code here:
    }//GEN-LAST:event_ckbmigorActionPerformed

    private void ckbmireActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ckbmireActionPerformed
        txtmire.setText("8000");// TODO add your handling code here:
    }//GEN-LAST:event_ckbmireActionPerformed

    private void txttotalnasgorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txttotalnasgorActionPerformed
        
        
    }//GEN-LAST:event_txttotalnasgorActionPerformed

    private void cbnasgorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbnasgorActionPerformed
        int jumlah = (int)cbnasgor.getSelectedIndex();
        double harga = Double.parseDouble(txtnasgor.getText());
        double total = jumlah * harga;
        txttotalnasgor.setText(Double.toString(total));
        
            
        
    }//GEN-LAST:event_cbnasgorActionPerformed

    private void cbmigorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbmigorActionPerformed
        int jumlah = (int)cbmigor.getSelectedIndex();
        double harga = Double.parseDouble(txtmigor.getText());
        double total = jumlah * harga;
        txttotalmigor.setText(Double.toString(total));// TODO add your handling code here:
    }//GEN-LAST:event_cbmigorActionPerformed

    private void cbmireActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbmireActionPerformed
        int jumlah = (int)cbmire.getSelectedIndex();
        double harga = Double.parseDouble(txtmire.getText());
        double total = jumlah * harga;
        txttotalmire.setText(Double.toString(total));// TODO add your handling code here:
    }//GEN-LAST:event_cbmireActionPerformed

    private void btntotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btntotalActionPerformed
        if(!ckbnasgor.isSelected()&!ckbmigor.isSelected() &!ckbmire.isSelected()){
           JOptionPane.showMessageDialog(this, "Makanan belum dipilih","Pesan Pemberitahuan",JOptionPane.ERROR_MESSAGE);
           return;
        }
        if ((ckbnasgor.isSelected() && cbnasgor.getSelectedIndex() == 0) ||
        (ckbmigor.isSelected() && cbmigor.getSelectedIndex() == 0) ||
        (ckbmire.isSelected() && cbmire.getSelectedIndex() == 0)) {
        
        JOptionPane.showMessageDialog(this, "Menu yang dipilih harus memiliki jumlah lebih dari 0!", "Peringatan", JOptionPane.WARNING_MESSAGE);
        return;
    }
        double a = Double.parseDouble(txttotalnasgor.getText());
        double b = Double.parseDouble(txttotalmigor.getText());
        double c = Double.parseDouble(txttotalmire.getText());
        double total = a+b+c;
        txttotal.setText(Double.toString(total));
    }//GEN-LAST:event_btntotalActionPerformed

    private void btnkeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnkeluarActionPerformed
        String total = txttotal.getText();
        utama.setTotalMakanan(total);
        this.dispose();
    }//GEN-LAST:event_btnkeluarActionPerformed

    private void btnresetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnresetActionPerformed
        ckbnasgor.setSelected(false);
        ckbmigor.setSelected(false);
        ckbmire.setSelected(false);
        cbnasgor.setSelectedIndex(0);
        cbmigor.setSelectedIndex(0);
        cbmire.setSelectedIndex(0);
        txttotalnasgor.setText("0");
        txttotalmigor.setText("0");
        txttotalmire.setText("0");
        txttotal.setText("0");
        txtnasgor.setText("0");
        txtmigor.setText("0");
        txtmire.setText("0");
        // TODO add your handling code here:
    }//GEN-LAST:event_btnresetActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(formmakanan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(formmakanan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(formmakanan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(formmakanan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new formmakanan().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnkeluar;
    private javax.swing.JButton btnreset;
    private javax.swing.JButton btntotal;
    private javax.swing.JComboBox<String> cbmigor;
    private javax.swing.JComboBox<String> cbmire;
    private javax.swing.JComboBox<String> cbnasgor;
    private javax.swing.JCheckBox ckbmigor;
    private javax.swing.JCheckBox ckbmire;
    private javax.swing.JCheckBox ckbnasgor;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField txtmigor;
    private javax.swing.JTextField txtmire;
    private javax.swing.JTextField txtnasgor;
    private javax.swing.JTextField txttotal;
    private javax.swing.JTextField txttotalmigor;
    private javax.swing.JTextField txttotalmire;
    private javax.swing.JTextField txttotalnasgor;
    // End of variables declaration//GEN-END:variables
}
