/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package pratikum29062026;

import javax.swing.JOptionPane;

/**
 *
 * @author Muhammad Zikri
 */
public class formminuman extends javax.swing.JFrame {

    /**
     * Creates new form formminuman
     */
    private formutama utama;
    public formminuman() {
        initComponents();
        txtteh.setEditable(false);
        txtkopi.setEditable(false);
        txtsusu.setEditable(false);
        txttotalteh.setEditable(false);
        txttotalkopi.setEditable(false);
        txttotalsusu.setEditable(false);
        txttotal.setEditable(false);
    }

    public formminuman(formutama utama) {
        this.utama = utama;
        initComponents();
        txtteh.setEditable(false);
        txtkopi.setEditable(false);
        txtsusu.setEditable(false);
        txttotalteh.setEditable(false);
        txttotalkopi.setEditable(false);
        txttotalsusu.setEditable(false);
        txttotal.setEditable(false);
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        cbteh = new javax.swing.JCheckBox();
        chkopi = new javax.swing.JCheckBox();
        cbsusu = new javax.swing.JCheckBox();
        txtteh = new javax.swing.JTextField();
        txtkopi = new javax.swing.JTextField();
        txtsusu = new javax.swing.JTextField();
        cxteh = new javax.swing.JComboBox<>();
        cxkopi = new javax.swing.JComboBox<>();
        cxsusu = new javax.swing.JComboBox<>();
        txttotalteh = new javax.swing.JTextField();
        txttotalkopi = new javax.swing.JTextField();
        txttotalsusu = new javax.swing.JTextField();
        btntotal = new javax.swing.JButton();
        txttotal = new javax.swing.JTextField();
        btnkembali = new javax.swing.JButton();
        btnreset = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel1.setText("Menu Minuman");

        cbteh.setText("Teh Manis");
        cbteh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbtehActionPerformed(evt);
            }
        });

        chkopi.setText("Kopi Hitam");
        chkopi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkopiActionPerformed(evt);
            }
        });

        cbsusu.setText("Susu");
        cbsusu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbsusuActionPerformed(evt);
            }
        });

        txtteh.setText("0");

        txtkopi.setText("0");

        txtsusu.setText("0");

        cxteh.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Jumlah", "1", "2", "3", "4", "5", " " }));
        cxteh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cxtehActionPerformed(evt);
            }
        });

        cxkopi.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Jumlah", "1", "2", "3", "4", "5", " " }));
        cxkopi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cxkopiActionPerformed(evt);
            }
        });

        cxsusu.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Jumlah", "1", "2", "3", "4", "5", " " }));
        cxsusu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cxsusuActionPerformed(evt);
            }
        });

        txttotalteh.setText("0");

        txttotalkopi.setText("0");

        txttotalsusu.setText("0");

        btntotal.setText("Total");
        btntotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btntotalActionPerformed(evt);
            }
        });

        txttotal.setText("0");

        btnkembali.setText("Keluar");
        btnkembali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnkembaliActionPerformed(evt);
            }
        });

        btnreset.setText("Reset");
        btnreset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnresetActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(194, 194, 194)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cbteh)
                                    .addComponent(chkopi)
                                    .addComponent(cbsusu))
                                .addGap(43, 43, 43)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtteh)
                                    .addComponent(txtkopi)
                                    .addComponent(txtsusu, javax.swing.GroupLayout.DEFAULT_SIZE, 85, Short.MAX_VALUE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(55, 55, 55)
                                .addComponent(btnreset, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(64, 64, 64)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnkembali, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(cxsusu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(21, 21, 21)
                                    .addComponent(txttotalsusu))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(btntotal)
                                    .addGap(18, 18, 18)
                                    .addComponent(txttotal, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(cxkopi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(cxteh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGap(21, 21, 21)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(txttotalteh)
                                        .addComponent(txttotalkopi)))))))
                .addContainerGap(41, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbteh)
                    .addComponent(txtteh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cxteh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txttotalteh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(chkopi)
                    .addComponent(txtkopi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cxkopi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txttotalkopi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbsusu)
                    .addComponent(txtsusu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cxsusu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txttotalsusu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(46, 46, 46)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btntotal)
                    .addComponent(txttotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 53, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnreset, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnkembali, javax.swing.GroupLayout.DEFAULT_SIZE, 47, Short.MAX_VALUE))
                .addGap(41, 41, 41))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cbtehActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbtehActionPerformed
        txtteh.setText("5000");
    }//GEN-LAST:event_cbtehActionPerformed

    private void chkopiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkopiActionPerformed
        txtkopi.setText("4000");// TODO add your handling code here:
    }//GEN-LAST:event_chkopiActionPerformed

    private void cbsusuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbsusuActionPerformed
        txtsusu.setText("3000");// TODO add your handling code here:
    }//GEN-LAST:event_cbsusuActionPerformed

    private void cxtehActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cxtehActionPerformed
        int jumlah = (int)cxteh.getSelectedIndex();
        double harga = Double.parseDouble(txtteh.getText());
        double total = jumlah * harga;
        txttotalteh.setText(Double.toString(total));// TODO add your handling code here:
    }//GEN-LAST:event_cxtehActionPerformed

    private void cxkopiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cxkopiActionPerformed
        int jumlah = (int)cxkopi.getSelectedIndex();
        double harga = Double.parseDouble(txtkopi.getText());
        double total = jumlah * harga;
        txttotalkopi.setText(Double.toString(total));// TODO add your handling code here:
    }//GEN-LAST:event_cxkopiActionPerformed

    private void cxsusuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cxsusuActionPerformed
        int jumlah = (int)cxsusu.getSelectedIndex();
        double harga = Double.parseDouble(txtsusu.getText());
        double total = jumlah * harga;
        txttotalsusu.setText(Double.toString(total));// TODO add your handling code here:
    }//GEN-LAST:event_cxsusuActionPerformed

    private void btntotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btntotalActionPerformed
        if (!cbteh.isSelected() && !chkopi.isSelected() && !cbsusu.isSelected()) {
        JOptionPane.showMessageDialog(this, "Harap pilih minimal satu menu minuman!", "Peringatan", JOptionPane.WARNING_MESSAGE);
        return;
    }
        
    if ((cbteh.isSelected() && cxteh.getSelectedIndex() == 0) ||
        (chkopi.isSelected() && cxkopi.getSelectedIndex() == 0) ||
        (cbsusu.isSelected() && cxsusu.getSelectedIndex() == 0)) {
        
        JOptionPane.showMessageDialog(this, "Menu yang dipilih harus memiliki jumlah lebih dari 0!", "Peringatan", JOptionPane.WARNING_MESSAGE);
        return;
        
    }
        double a = Double.parseDouble(txttotalteh.getText());
        double b = Double.parseDouble(txttotalkopi.getText());
        double c = Double.parseDouble(txttotalsusu.getText());
        double total = a+b+c;
        txttotal.setText(Double.toString(total));// TODO add your handling code here:
    }//GEN-LAST:event_btntotalActionPerformed

    private void btnkembaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnkembaliActionPerformed
        String total = txttotal.getText();
        utama.setTotalMinuman(total);
        this.dispose();// TODO add your handling code here:
    }//GEN-LAST:event_btnkembaliActionPerformed

    private void btnresetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnresetActionPerformed
        cbteh.setSelected(false);
        chkopi.setSelected(false);
        cbsusu.setSelected(false);
        cxteh.setSelectedIndex(0);
        cxkopi.setSelectedIndex(0);
        cxsusu.setSelectedIndex(0);
        txttotalteh.setText("0");
        txttotalkopi.setText("0");
        txttotalsusu.setText("0");
        txttotal.setText("0");
        txtteh.setText("0");
        txtkopi.setText("0");
        txtsusu.setText("0");
        // TODO add your handling code here:
    }//GEN-LAST:event_btnresetActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(formminuman.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(formminuman.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(formminuman.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(formminuman.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new formminuman().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnkembali;
    private javax.swing.JButton btnreset;
    private javax.swing.JButton btntotal;
    private javax.swing.JCheckBox cbsusu;
    private javax.swing.JCheckBox cbteh;
    private javax.swing.JCheckBox chkopi;
    private javax.swing.JComboBox<String> cxkopi;
    private javax.swing.JComboBox<String> cxsusu;
    private javax.swing.JComboBox<String> cxteh;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField txtkopi;
    private javax.swing.JTextField txtsusu;
    private javax.swing.JTextField txtteh;
    private javax.swing.JTextField txttotal;
    private javax.swing.JTextField txttotalkopi;
    private javax.swing.JTextField txttotalsusu;
    private javax.swing.JTextField txttotalteh;
    // End of variables declaration//GEN-END:variables
}
